### ISSUE TITLE
ImmutableEnumChecker should respect javax.annotation.concurrent.Immutable

### ISSUE THREAD

**Issue by shemnon** [google/error-prone#1142]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?

2.3.2

### Does this issue reproduce with the latest release?

Yes

### What did you do?

An existing enum has a field that is annotated with javax.annotation.concurrent.Immutable instead of the Google annotation.

### What did you expect to see?

I expected it to not fail the check since the type of the field was annotated with @Immutable

### What did you see instead?

A failure because the checker required the google annotation (com.google.errorprone.annotations.Immutable) instead of the JSR-305 annotation (javax.annotation.concurrent.Immutable).

**Comment by jbduncan** [comment]
Hi @shemnon. I could be wrong about this, but I believe that the reason error-prone doesn't allow using `@javax.annotation.concurrent.Immutable` (anymore?) is because of conflicts that the `javax.*` sub-packages from different projects/sources cause for each other when they're included on the new `--module-path` rather than the classic `--classpath`.

@cushon Is my understanding correct? Or is there a different reason for this behaviour occuring in error-prone?

**Comment by shemnon** [comment]
Note I am running this in Java 8, so module-path is meaningless to me in that context.  I think it's too soon to throw the Java 8 baby out with the classpath bathwater.  Doubly so since module adoption in Java 9+ is quite low still.

**Comment by trejkaz** [comment]
Having classes in `javax.annotation.concurrent` doesn't prevent you having classes in `javax.*` in other modules anyway, right? That rule only applies if it's the same module.

**Comment by cushon** [comment]
#612
