### ISSUE TITLE
EqualsGetClass description is confusing

### ISSUE THREAD

**Issue by mernst** [google/error-prone#1172]
https://errorprone.info/bugpattern/EqualsGetClass says
> "Requiring the argument to equals to be of a specific concrete type is incorrect,"

but Error Prone rejects code that is not this pattern.
(Maybe Error Prone rejects any use of `getClass()` in the `equals` method? Anyway, it rejects seemingly-correct code that uses `getClass()`, but never compares it to a concrete type.)
I suggest that either the Error Prone check be changed, or the text be changed, so that they are consistent.

The discussion never gives an example of wrong code (that, a poorly-structured `equals` implementation).
I suggest that an example be added, both in the "The problem" section and also in the "Extending a value class to add attributes".

The current text assumes the reader is very familiar with the details of the cited Bloch book.
The text references an `.asPoint()` method without describing it.  The text also seems to assume that the reader knows the `equals()` implementation that the author has in mind.
Much of the text of https://errorprone.info/bugpattern/EqualsGetClass is about whether subclassing or composition is a better way to extend classes.  I think the text would be clearer if it focused on the problem with equality, and made it concrete.
I suggest replacing most of the text with a succession of 2 or 3 equals() methods, showing a bad one and a good one.

Or, if the pattern is really "use composition instead of subclassing", then please give the pattern a different name (not EqualsGetClass) that makes clear that the problem is not the `equals` method, but the larger design. 

Related: #1144 has a discussion that the current text could be improved (and that the check itself may be a bit too aggressive), but that predated the version of the text that I read. The edits that came about as a result of that discussion actually removed specifics like examples of `equals` methods.  So I'm sorry to complain about the result of an attempt to fix a problem. :-/

**Comment by henryptung** [comment]
Would add on to this ticket that this passage, in particular, seems to minimize the importance of `.equals()` symmetry and almost seems to indicate it's not important:

> Unfortunately, `equals` now creates a big problem. Two `Points` should be seen
as interchangeable whenever they have the same `x` and `y` coordinates. But two
`ColoredPoints` are only equivalent if their coordinates *and* color are the
same. This, plus the general contract of `equals` (e.g. symmetry), ends up
forcing `Point(1, 2)` to respond `false` if asked whether it is equal to
`ColoredPoint(1, 2, BLUE)`.

> This can be achieved by changing `equals` to be based on `getClass` instead of
`instanceof`. But do we even want to do **that**? Recall the main advantage we cited
for using subtyping: so that we "can pass `ColoredPoint` to anything that
expects a `Point`", we said. Yet we are in fact *not* achieving that after all.
Put simply, `ColoredPoint` is incapable of functioning properly *as a `Point`*
because it cannot participate in equality checks with other `Point`s.

It's not clear here what **that** refers to, and could be read as the last major concept brought up (general contract of `equals`, symmetry).

More broadly, the document doesn't distinguish between the separate concerns of `Point.equals` and `ColoredPoint.equals`. The correct solution (and the one I'm assuming is being advocated for) is that `Point.equals` uses `instanceof Point`, and **`ColoredPoint.equals` does not exist at all** (i.e. **do not override nontrivial `.equals` implementations**). The current documentation makes little effort to clarify this approach, allowing for the easy misinterpretation of "`Point.equals` uses `instanceof Point`, `ColoredPoint.equals` uses `instanceof ColoredPoint`".

**Comment by cushon** [comment]
The latest version of the documentation tries to put more emphasis on symmetry and the idea that the recommendation is to not use inheritance to model examples like `Point` / `ColoredPoint` e.g. with https://github.com/google/error-prone/commit/974f48057a0de49151a99020c33efc286cb5c612#diff-eb5c596b9b92f6e8dc6c2c981392f3f106dfcd336aa445145057ed182b4cf281
