### ISSUE TITLE
error-prone release schedule

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#1415]
### Description of the problem / feature request:

Is there an error-prone release schedule? The documentation at https://errorprone.info/bugpatterns references patterns from master that do not exist in any published release.

In particular I'm keen to try `InterruptedExceptionSwallowed`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd really appreciate a structured release schedule, perhaps once a month?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open https://github.com/google/error-prone/releases or check maven central.

### What version of Error Prone are you using?

2.3.3.

###  Have you found anything relevant by searching the web?

No, neither https://groups.google.com/forum/#!forum/error-prone-discuss nor this project document a release schedule or roadmap.

Thanks for your help!

**Comment by floscher** [comment]
On the same day that you opened this issue, a commit was [tagged as `2.3.4`](https://github.com/google/error-prone/releases/tag/2.3.4) (note the missing leading `v`, hopefully this doesn't break anything in the [release process](https://github.com/google/error-prone/wiki/Releasing#releasing)).
So the next release seems to be right around the corner. Unfortunately I have no idea how long it will take for the maintainers to release. For `2.3.3` they needed almost one month from pushing the git-tag to publishing the release, for `2.3.2` they needed less than 48 hours.

**Comment by cushon** [comment]
Sorry for not responding here sooner. (There have at least been releases since this was filed, so it it should be possible to try out `InterruptedExceptionSwallowed` :)

We had been trying to do releases roughly every two months, but we obviouslybviously haven't been keeping to that schedule. I'm not sure we'll be able to promise a monthly cadence, but I am going to try to make more releases happen this year than last year.
