### ISSUE TITLE
Unintended type parameters named "String," etc.

### ISSUE THREAD

**Issue by cushon** [google/error-prone#156]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=156) created by **cpovirk@google.com** on 2013-07-03 at 01:22 AM_

---

Occasionally, a user who intends to define a class that implements a specialized generic interface will inadvertently write "&lt;String&gt;" twice, once for the interface he's implementing and once for his own class. For example, note the "MyComparator&lt;String&gt;" below:

&nbsp;&nbsp;static class MyComparator&lt;String&gt; implements Comparator&lt;String&gt; {
&nbsp;&nbsp;&nbsp;&nbsp;@﻿Override public int compare(String a, String b) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return compareStrings(a, b);
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}

This can lead to confusing errors like "incompatible types required: String found: java.lang.String," as in this StackOverflow question:

http://stackoverflow.com/q/8443892/28465

An error-prone check for type parameters named "&lt;String&gt;" would probably catch 95% of these errors. The check _might_ get a few more percent by looking for other common JDK class names, but I suspect that most of the remaining 5% would instead happen with custom user classes.

(In an ideal world, I'd be inclined to reject any type parameter with a ClassNameStyle name, conveniently catching all these errors, but that's unrealistic.)

Here are a couple searches that turn up instances of this problem in Google code. (One of those instance is about to be fixed. That fix is what led me to file this feature request.)

'(class|interface) \w+&lt;String&gt;'

'(class|interface) \w+&lt;[A-Z][a-z]\w+&gt;\s+implements Comparator'

**Comment by cushon** [comment]
This is covered by http://errorprone.info/bugpattern/JavaLangClash.

**Comment by cpovirk** [comment]
Someone just reported a similar problem internally but with "Bigtable" instead of "String." I'm not sure that there's much we can realistically do to detect this, though. (In fact, in this particular case, the error that the user got was from trying to call a method on type parameter `Bigtable`. IIRC, Error Prone would already have issued an error there, if only the compilation hadn't failed already because the method doesn't exist on `Object` :)) FWIW, my searches above no longer turn up any true positives.

**Comment by cpovirk** [comment]
(And thanks for `JavaLangClash`!)
