### ISSUE TITLE
Erroneous Class Compare

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/error-prone#2052]
Class name comparisons should not be used to identify the type of object
https://github.com/google/error-prone/blob/50e2e7b54215f8fc0e2b6d82e3667a12f0f6e530/check_api/src/main/java/com/google/errorprone/BugCheckerInfo.java#L122
https://github.com/google/error-prone/blob/50e2e7b54215f8fc0e2b6d82e3667a12f0f6e530/core/src/main/java/com/google/errorprone/refaster/Template.java#L485
Use class comparisons to identify the type of the object

**Comment by cushon** [comment]
There are situations where reflection should be used instead of testing for classes by name, but in the case of a compiler or static analysis tool like Error Prone we don't generally want to interact with elements in the compilation using reflection. It's possible to use reflection / class literals for `java.lang.SuppressWarnings` because it's part of the JDK so it's guaranteed to be on the compiler's runtime classpath, but that isn't true in general. I don't see anything wrong with the way this code is currently written.
