### ISSUE TITLE
Compile time checks for class initialization deadlocks

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#2062]
### Description of the problem / feature request:

Class initialization deadlocks are common when a type uses one of its subtypes in a static field or block.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to catch these deadlocks at compile time rather than intermittently at runtime!
I have implemented such a check here, but I believe it would be a good candidate for error-prone upstream:

https://github.com/palantir/gradle-baseline/pull/1598

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example from guava:
https://github.com/google/guava/issues/1977

```java
class Base {
  static final Object FIELD = new Sub();
  static class Sub implements Base {
  }
}
```
### What version of Error Prone are you using?

2.4.0

###  Have you found anything relevant by searching the web?

no

**Comment by carterkozak** [comment]
@cushon, I'm interested in your thoughts on this when you have a moment.

**Comment by cushon** [comment]
> I believe it would be a good candidate for error-prone upstream

@carterkozak sorry for the very slow response here, are you still interested in contributing this?

**Comment by carterkozak** [comment]
No worries, @cushon. I'd be happy to :-)

**Comment by cushon** [comment]
Great, thanks!

**Comment by hagbard** [comment]
I assume that for AutoValue, and assuming that the generated subclass only gets referenced after static initialization of the parent class has started (i.e. all references to "new AutoValue_Xxx(...)" occur inside the parent class), that this is not an issue?

**Comment by cushon** [comment]
@hagbard I think it would be theoretically possible to create deadlocks that involved `AutoValue`, but not with idiomatic usages of it, normally the hand-written class doesn't reference the generated subclass in static field initializers.

I guess we might have to be careful about stuff like

```java
class Base {
  static final Object DEFAULT = new AutoValue_Base();
}
```

@carterkozak I'd still be happy to review a PR for this if you have time and interest :)

**Comment by eamonnmcmanus** [comment]
We already have [`AutoValueSubclassLeaked`](https://errorprone.info/bugpattern/AutoValueSubclassLeaked) to guard against the most likely source of initialization deadlocks involving AutoValue. I don't think there's a concern with this sort of thing:

```java
@AutoValue
abstract class Base {
  abstract String bar();

  static final Object DEFAULT = new AutoValue_Base("bar");

  static Base of(String bar) {
    return new AutoValue_Base(bar);
  }
}
```

If those are the only references to `AutoValue_Base` then there's no path by which a thread could start initializing `AutoValue_Base` before `Base`. If there were an Error Prone like the proposed one, it would trigger here. Users could work around that by writing `of("bar")` instead of the constructor call, though that in itself would not change the possibility or impossibility of deadlocking.

The text below gives more detail, but isn't all that relevant to the issue here, so take it as a footnote.

----

We've encountered a couple of cases at Google where people have used AutoValue with builders in a way that could lead to deadlock. I'm copying some excerpts from our internal issue-tracking system:

```java
@AutoValue
public abstract class Foo {
  public static final Foo DEFAULT = Builder.builder().build();

  @AutoValue.Builder
  public abstract static class Builder {
    public static Builder builder() {
      return new AutoValue_Foo.Builder();
    }
    public abstract Foo build();
  }
}
```
Suppose none of these classes has been initialized, and two threads come along at the same time. Thread A references `Foo.DEFAULT` and Thread B calls `Foo.Builder.builder().build()` directly. Thread A will then try to initialize classes in this order: `Foo` > `Foo.Builder` > `AutoValue_Foo.Builder` > `AutoValue_Foo`. Thread B will try to initialize in this order: `Foo.Builder` > `AutoValue_Foo.Builder` > `AutoValue_Foo` > `Foo`. Because A's order has `Foo` before `Foo.Builder` and B's order has it after, the threads may deadlock.

If the static `builder()` method were in `Foo` we would have this:

```java
@AutoValue
public abstract class Foo {
  public static final Foo DEFAULT = builder().build();
  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Foo build();
  }
}
```

Now A still references `Foo.DEFAULT` but B calls `Foo.builder().build()`. A's order is: `Foo` > `AutoValue_Foo.Builder` > `Foo.Builder` > `AutoValue_Foo`. B's order is the same. So no deadlock.

AutoValue attempts to detect and [warn about](https://github.com/google/auto/blob/ae819d5d8c82dccf864862be483b6038f6d60929/value/src/main/java/com/google/auto/value/processor/BuilderSpec.java#L309-L312) this particular pattern but it's still possible to run into it if your code doesn't match exactly what AutoValue is checking for or if you have a hand-written builder.

**Comment by cushon** [comment]
> No worries, @cushon. I'd be happy to :-)

@carterkozak any chance this is still on your radar? :)

---

A couple more examples of class initialization deadlocks:

* https://github.com/raphw/byte-buddy/issues/1347
* https://github.com/bazelbuild/bazel/pull/21608

**Comment by cushon** [comment]
An initial implementation has been added in https://github.com/google/error-prone/commit/1d994843280a97e12e31777c3f3c02f483fbbac8.

Feedback or contributions are very welcome, e.g. if there are ideas about the heuristics or how to make it more precise.
