### ISSUE TITLE
Octal literals, e.g. 'int i = 010;' are arguably evil

### ISSUE THREAD

**Issue by cushon** [google/error-prone#227]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=227) created by **kevinb@google.com** on 2014-01-16 at 07:09 PM_

---

I just finished swearing up and down that the integer literal 010 would equal ten, not eight.  How embarrassing.

If we have managed to get the 'l' suffix error to work, it might be worth considering a check that forbids all octal literals as well.

**Comment by eaftan** [comment]
/cc @kevinb9n
I revived this and wrote a prototype checker.  My first pass flagged all octal literals, and of the ~50 instances I looked at, all were correct.  The usages fell into 2 buckets:

1) Specifying months and days in dates, e.g. 'new Date("2014", "10", "01")'.  These are OK because they parse as the same value whether they are octal or decimal.  The only concern here is if you modify the date to either "08" or "09", you will get a compile error as those are not valid octal values.  So you might waste some time understanding the error message, but they are not strictly a correctness issue.  

2) Filesystem permissions, e.g. 'chmod(file, 0755)'.  These are also OK because filesystem permissions are octal.

I'm going to update the prototype check to only flag octal values that are not of length 2 or 4.  That should weed out these legitimate cases.

**Comment by eaftan** [comment]
I special cased my prototype checker to flag octal values that are not of length 2 or 4, to avoid the date and filesystem permissions false positives, but most of the hits were still false positives.  I think octal literals may not actually be evil.  Closing as will not fix.

**Comment by kevinb9n** [comment]
Okay then. Good to know. Thanks for digging into it.

On Tue, Jan 27, 2015 at 9:16 PM, Eddie Aftandilian <notifications@github.com
> wrote:

> I special cased my prototype checker to flag octal values that are not of
> length 2 or 4, to avoid the date and filesystem permissions false
> positives, but most of the hits were still false positives. I think octal
> literals may not actually be evil. Closing as will not fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/error-prone/issues/227#issuecomment-71782383>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
