### ISSUE TITLE
Proposed pattern: `... || foo.equals(null)` ~~> `foo.equals(null) || ...`

### ISSUE THREAD

**Issue by TomMD** [google/error-prone#2274]
### Feature requests: what underlying problem are you trying to solve with this feature?

I saw a real life example of code in the form:

```
name.equals("") || name.equals(null)
```

And the reviewer suggestion was:

```
name.equals(null) || name.equals("") 
```

Would a PR with a new bug pattern so errorprone can catch this be acceptable? Obviously we don't want to trigger on `a.equals(null) || b.equals(null)` with a suggestion of `b.equals(null) || a.equals(null)` but we can ignore order of null checks as long as we know to take that case into account.

**Comment by cushon** [comment]
The contract for equals requires that `a.equals(null)` always returns false: https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-

Did the implementation of `name` in your example do something different?

I think always warning on `name.equals(null)` might make sense, since the result should always be `false`, and the intent might have been `name != null` ?

**Comment by TomMD** [comment]
Ah, of coarse.  Actually the error shouldn't be what I asked at all then.  We the added error would be `a.equals(null)` is a long way of spelling `false`.

**Comment by cpovirk** [comment]
https://github.com/google/error-prone/commit/53545d6e64fc995a45a184384451aa19f55b514b
