### ISSUE TITLE
Introduce @ReferenceEqualitySafe class annotation to avoid triggering ReferenceEquality check

### ISSUE THREAD

**Issue by tereigo** [google/error-prone#2818]
Sometimes there are Java classes which are safe to compare using '==' operator, like Java enums.
It can be the special custom made Enum classes for instance or some other classes which instances are controlled and managed to ensure there is only one instance for a given value.

Currently errorprone raises ReferenceEquality warning for such classes because they are Java Objects after all.

It would be nice to be able to mark such classes with @ReferenceEqualitySafe annotation so that errorprone could ignore the comparison of such objects via '==' operator

Example:
```java
public final class ObjectId {
    public static final ObjectId ID1 = new ObjectId(1);
    public static final ObjectId ID2 = new ObjectId(2);

    private final int value;

    private ObjectId(int v) {
        this.value = v;
   }

    public static ObjectId valueOf(int v) {
       switch (v) {
        case 1: 
            return ID1;
        case 2: 
            return ID2;
        }
       throw new IllegalArgumentException();      
    }
}

ObjectId id1 = ObjectId.ID1;
boolean b = id1 == ObjectId.ID2;
```

**Comment by graememorgan** [comment]
Internally at least, we tend to prefer using `equals` even for cases where reference equality is safe, because `equals` is more self-evidently correct.

Is there a reason to actively prefer using reference equality?

**Comment by tereigo** [comment]
A couple of things I can think of:
1. We migrated some widely used Java enums to this kind of implementation and so now have to update a lot of places where these reference comparisons are done although it doesn't bring any value because the semantics is still the same.
2. Comparing 2 references is not like-for-like with "obj1.equals(obj2)" since it doesn't account for obj1 being null. So to be equivalent it should be smth like: "(obj1 == null && obj2 == null) || (obj1 != null && obj1.equals(obj2)" which looks rather cumbersome.
3. And comparing such classes with `==` looks simpler and feels more natural than via 'equals'

After all it's up to the code owner to mark the classes with the proposed tags because he/she knows the usage semantics of it

**Comment by cushon** [comment]
We try to be fairly conservative about adding new annotations to Error Prone. If we don't add this, and you want to get some of the benefits of `ReferenceEquality` with a way to suppress it for these classes, one alternative would be to define your own annotation and creating a plugin check similar to `ReferenceEquality`.

> We migrated some widely used Java enums to this kind of implementation

Can you share any details about why you needed to migrate away from enums for this? That sounds like it may be a somewhat uncommon use-case.

> `(obj1 == null && obj2 == null) || (obj1 != null && obj1.equals(obj2)`

I'd recommend [`java.util.Objects.equals`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Objects.html#equals(java.lang.Object,java.lang.Object)) for null-tolerant `equals` tests

**Comment by tereigo** [comment]
There might be different reasons to introduce custom-made classes which should have 1 instance per value, not necessarily Enums I guess.
In our case we need to provide special wire serialization of such enums into binary and allow them to be dynamic enums meaning that enum values can be added at runtime. But the semantics and usage of such objects are still enum-like.

**Comment by graememorgan** [comment]
I think it's totally reasonable to introduce custom-made classes with exactly 1 instance per value, but is there a strong reason to prefer `==` over `equals` (be that `a.equals(b)` or `equals(a, b)` for null tolerance) for those?

**Comment by tereigo** [comment]
no big reason apart from having to update a lot of code but not because the new code will be cleaner/safer but just to satisfy the code validation tool

**Comment by kevinb9n** [comment]
Recommend closing this.

Identity equality and hash code exist for system-level purposes where what the client code cares about is instances _per se_ and not what they represent. For such code _all_ classes are reference-equality safe no matter what an annotation says. However, 99.9% of code cares about what the instances represent, not the instances themselves. So classes are empowered to decide when to consider instances indistinguishable and when not. For this code, `==` is _never_ correct, it is _purely_ a syntactic sugar, that developers yearn to use because Java's language design isn't ideal.

What these developers want to do is write code that _asks the wrong question_, because they're convinced they should safely get the same answer as the question they really mean. I don't think EP should do anything that encourages that, however indirectly. Use `equals` and shake your fist at Java every time.

Relevant: as Java progresses, more and more usages of `==` can be profitably changed to `switch`, which sidesteps this whole `==/equals` problem, and should be encouraged.
