### ISSUE TITLE
Errorprone not an OSGi bundle

### ISSUE THREAD

**Issue by Lana11s** [google/error-prone#2967]
Currently, com.google.errorprone.annotations (version 2.10.0) is not an OSGi bundle. Some entries are missing in MANIFEST.MF:

```
Manifest-Version: 1.0
Automatic-Module-Name: com.google.errorprone.annotations
Archiver-Version: Plexus Archiver
Built-By: cushon
Created-By: Apache Maven 3.6.3
Build-Jdk: 1.8.0_202
```

Would be great if you can change this. Would allow us to upgrate to google/guice 5.1.0

**Comment by Lana11s** [comment]
Hello @cushon,
I looked into previous releases of error-prone (incl. 2.0) and manifest file had the same structure.
Guice worked in the OSGi environment because the dependency to error-prone was introduced with 5.1.0.
I am not familiar with Maven Jar Plugin, but it seems that it needs some configuration so that entries (like import-package, export-package) are added: https://maven.apache.org/plugins/maven-jar-plugin/examples/manifest-customization.html

**Comment by cdietrich** [comment]
i also just stumbled on this issue when testing the new guice

**Comment by HannesWell** [comment]
@cushon if you are interested I can provide a PR to implement this (probably next week).

> I am not familiar with Maven Jar Plugin, but it seems that it needs some configuration so that entries (like import-package, export-package) are added: https://maven.apache.org/plugins/maven-jar-plugin/examples/manifest-customization.html

It is simpler to use the [`maven-bundle-plugin`](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html) or [`bnd-maven-plugin`](https://github.com/bndtools/bnd/blob/master/maven-plugins/bnd-maven-plugin/README.md), because they can generate high quality OSGi metadata out of the box and can be fine tuned as necessary.
The latter plugin is used by the former one under the hood, which is why I recommend to use the latter one.

**Comment by HannesWell** [comment]
Just created https://github.com/google/error-prone/pull/3903. Everybody interested, please join the discussion there.
