### ISSUE TITLE
[ReturnValueIgnored] Return value of 'collect' must be used

### ISSUE THREAD

**Issue by retrodaredevil** [google/error-prone#3292]
I am getting a warning for code like this:

```
r.stream().map(StoredPacketGroup::getStoredIdentifier).collect(Collectors.toCollection(() -> processed));
```
where `processed` is an already created list.

In this case, the return value of collect is not useful to me, because the values I need have been added to `processed`. Can this issue be fixed for certain types of `collect` calls?

**Comment by Stephan202** [comment]
Hmm, in this case, shouldn't one instead prefer this simpler and `ReturnValueIgnored`-compatible alternative?
```java
r.stream().map(StoredPacketGroup::getStoredIdentifier).forEach(processed:add);
```

(Or with `forEachOrdered` instead of `forEach`, as applicable.)

[This SO answer](https://stackoverflow.com/a/22755993/74939) is a nice read, which points out several issues with the `Collectors.toCollection(() -> processed)` construct.

**Comment by retrodaredevil** [comment]
I will not be using `collect` anymore for this purpose. Thanks for linking that SO answer. Good stuff.
