### ISSUE TITLE
Discourage APIs locale-dependent APIs like String.to{Lower,Upper}Case

### ISSUE THREAD

**Issue by cushon** [google/error-prone#3809]
Inspired by https://github.com/bazelbuild/bazel/pull/17687

> Java's `String#to{Lower,Upper}Case()` is locale-dependent, which can
> lead to unexpected results in locales with special case mappings in the
> ASCII range (e.g. in a Turkish locale, a capital ASCII `I` lowercases to
> a non-ASCII variant of `i`).

We have an internal refaster template that suggests `com.google.common.base.Ascii`, so we'd get this for free from https://github.com/google/error-prone/issues/649

**Comment by fmeum** [comment]
@cushon Given that #649 has an unclear status, would you accept contributions for this?

**Comment by cushon** [comment]
Yes, absolutely

**Comment by rickie** [comment]
In Error Prone Support we have the `StringCaseLocaleUsage` check ([link](https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringCaseLocaleUsage.java)) exactly for this purpose. 

We made it an Error Prone check, instead of a Refaster template, to show both `Locale.ROOT` and `Locale.getDefault()` in the suggested fix. We don't use the option to have multiple after-templates per Refaster rule. 

We are definitely open to contributing this rule upstream (possibly with some tweaks to the BugPattern for e.g. the order of suggested fixes?). Would that be an option?

(Look [here](https://error-prone.picnic.tech/bugpatterns/StringCaseLocaleUsage/) to see some extra documentation on the check.)

**Comment by rickie** [comment]
Filed https://github.com/google/error-prone/pull/3813.
