### ISSUE TITLE
Proposal: checker to prevent other checkers from calling javac methods that changed across JDKs

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#4026]
Error Prone has run into a couple issues lately where building on JDK 17 caused incompatibility with JDK 11, due to changes in javac APIs:

https://github.com/google/error-prone/issues/3895
https://github.com/google/error-prone/issues/2330

NullAway is running into these exact same issues:

https://github.com/uber/NullAway/pull/779
https://github.com/uber/NullAway/pull/795

It might be nice to have a checker that flags when other checkers are calling the methods whose signatures have changed.  Maybe just like the `DoNotCallChecker` but a separate implementation?  This way checkers could share knowledge on what calls to avoid moving forward.  (This kind of issue will get caught if tests are configured to run on older JDKs, which NullAway does now, but we still missed https://github.com/uber/NullAway/issues/794 due to a lack of unit test coverage.)

**Comment by cushon** [comment]
This SGTM.

I created [`ASTHelpersSuggestions`](https://github.com/google/error-prone/commits/master/core/src/main/java/com/google/errorprone/bugpatterns/ASTHelpersSuggestions.java) as a partial solution to this, e.g. for the `com.sun.tools.javac.util.Filter` issue there's a wrapper API in `ASTHelpers`, and that check suggests using the wrapper API.

I'd be happy to review PRs to improve coverage in this area. It might make sense to add additional APIs to `ASTHelpersSuggestions`, and maybe rename the check.

This could also potentially be a separate check if not all of the issues have `ASTHelpers` workarounds, or if that would be more useful. I saw in https://github.com/uber/NullAway/pull/779 that you used your own wrapper API because you weren't on Error Prone 2.20.0 yet. Would it be good enough to have a check that caught these issues and suggested `ASTHelpers`, since even if you could apply the fix as-is the finding would still be useful?

**Comment by msridhar** [comment]
The `ASTHelpersSuggestions` check looks like exactly what I was looking for!  Thanks for the pointer!  In fact we were already running the check :-)  But it seems to have missed the following bad call to a `Scope` method:

https://github.com/uber/NullAway/blob/48772af91a0fa9d6d1dc0dd825beb5cbcedf0e0c/nullaway/src/main/java/com/uber/nullaway/handlers/LombokHandler.java#L51

I tried turning up `ASTHelpersSuggestions` to `ERROR` but it still didn't get caught (and we shouldn't need to turn it up anyway since we build with `-Werror`).  The code in `ASTHelpersSuggestions` looks correct to me.  Any idea what might be going on or if this is a bug?  

> Would it be good enough to have a check that caught these issues and suggested ASTHelpers, since even if you could apply the fix as-is the finding would still be useful?

Yes, as long as it flags issues this is still very useful to us, even if we can't apply the auto-fix.

**Comment by cushon** [comment]
I'm going to close this out now that https://github.com/google/error-prone/pull/4029 has landed, thanks!

> didn't have a good idea on what to rename the check to exactly

I don't have any brilliant ideas for this either, but proposals are welcome if you think of a name that would be clearer.
