### ISSUE TITLE
-XepPatch flags appear not to work

### ISSUE THREAD

**Issue by clonetwin26** [google/error-prone#487]
Working off this since documentation is sparse.
https://github.com/google/error-prone/commit/de639a1ef4d962b984741ed346f0519c85eb6122

Tried both settings. Can't get the patch files to show up or patch in place working. Wondering if there is anything more to this than passing the flags.

**Comment by nglorioso** [comment]
Hey clonetwin26!

Thanks for looking into it. It's not documented, because it's still a bit half-baked :)

Can you try following the integration pattern in https://github.com/google/error-prone/blob/master/examples/maven/pom.xml ? (compiling with -Pfixerrors should trigger the compiler flag as appropriate). If that doesn't work, any stacktraces or other errors you could provide would be helpful.

Thanks!

**Comment by cushon** [comment]
We'll update the documentation once this feature is ready to go.
