### ISSUE TITLE
specific case CollectionIncompatibleType

### ISSUE THREAD

**Issue by regrog** [google/error-prone#496]
Hi,
I have something like this and the compilation gives me the error CollectionIncompatibleType.
I know this is a very strange case but maybe you can improve the check.

myMap.get(val12) returns the right string value

```
public class MyMain {

	public static void main(String[] args) {

		Map<String, String> myMap = new HashMap<>();

		MyValue val11 = new MyValue("1", "1");
		MyValue val12 = new MyValue("1", "2");

		myMap.put(val11.getFullValue(), "val11");
		myMap.put(val12.getFullValue(), "val12");

		System.out.println(myMap.get(val12));

	}

	public static class MyValue {
		private final String value1;
		private final String value2;

		public MyValue(String value1, String value2) {
			this.value1 = value1;
			this.value2 = value2;
		}

		public String getValue1() {
			return value1;
		}

		public String getValue2() {
			return value2;
		}

		public String getFullValue() {
			return value1 + "." + value2;
		}

		@Override
		public boolean equals(Object myValueObject) {
			if (myValueObject instanceof String)
				return getFullValue().equals(myValueObject);
			else if (myValueObject instanceof MyValue) {
				MyValue entity = (MyValue) myValueObject;
				if (entity.getValue1().equals(getValue1()) && entity.getValue2().equals(getValue2()))
					return true;
			}

			return super.equals(myValueObject);
		}

		@Override
		public int hashCode() {
			return getFullValue().hashCode();
		}

		@Override
		public String toString() {
			return getFullValue();
		}
	}
}
```

**Comment by nglorioso** [comment]
Hello! TL;DR: No. 

MyValue's `equals` method violates the symmetric property of equals, since `String.equals(MyValue)` would return false, even if `MyValue.equals(String)` would return true: https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)

It may happen to be that HashMap checks equals by using the passed-in key.equals(the value stored in the map), but if it did it the opposite way, you couldn't look up by `val12`.

I suggest one of the following:
* Changing your Map to `Map<MyValue, String>` (if that's what you're querying by)
* Changing your get call to a more appropriate `map.get(val12.getFullValue())`
* If you really really must, use `@SuppressWarnings("CollectionIncompatibleType")` in the surrounding code (but note the underlying implementation issue you're relying on is still a thing).
