### ISSUE TITLE
Ignore CheckReturnValue if in a @Test(expected = Exception.class)

### ISSUE THREAD

**Issue by bramp** [google/error-prone#576]
Similar to #446 it is common to have JUnit code like this:

```java
@Test(expected = NullPointerException.class)
public void testNullName() {
   user.setName(null);
}
```

In this case a CheckReturnValue error occurs, where in this test code we are ensuring a NullPointerException would be thrown, so would never actually check the return value.

**Comment by mattnelson** [comment]
I would argue that using the `@Test(expected = ?)` pattern is itself a bug. You are only testing that an exception of the same type was thrown. Not that the exception you expected to be thrown was thrown for the reason expected. Creating a new rule that chains off this pattern feels wrong.

In the example provided you can't assert if the NPE was thrown because `user` was null or because null was passed into `setName`

**Comment by bramp** [comment]
You make a valid point in the usefulness of this kind of junit test, however, two issues:

1) My example was a copy and paste (with minor modification) of https://github.com/junit-team/junit4/wiki/exception-testing#trycatch-idiom which uses a similar pattern that has the same weakness (not knowing if the NPE is because user was null, or if setName throw it), and 
2) This is the first way [JUnit suggests](https://github.com/junit-team/junit4/wiki/exception-testing) you do this kind of testing.

Not supporting this use case, makes it difficult to migrate a existing projects to use error-prone.

**Comment by cushon** [comment]
I think this (and #446) would be reasonable to support, but they're low priority for us because we're been migrating away from `@Test(expected=...)` and `ExpectedException` to `assertThrows`/`expectThrows` because they make it significantly easier to write correct tests. (see [TestExceptionChecker](http://errorprone.info/bugpattern/TestExceptionChecker), [ExpectedExceptionChecker](http://errorprone.info/bugpattern/ExpectedExceptionChecker))

**Comment by cushon** [comment]
I'd forgotten we already do this for `assertThrows` and `ExpectedException`, so there's precedent.

**Comment by cushon** [comment]
Closing since we're unlikely to get to this especially now that `assertThrows` made it into a JUnit 4.x release.

**Comment by cushon** [comment]
Closing since we're unlikely to get to this especially now that `assertThrows` made it into a JUnit 4.x release.
