### ISSUE TITLE
Document the bytecode output produced by Error Prone

### ISSUE THREAD

**Issue by leventov** [google/error-prone#620]
I'm struggling to find any documentation on what kind of bytecode output Error Prone tool produces. The readme page on Github says that Error Prone is a "static analysis tool", that makes me think that Error Prone should produce exactly the same output as `javac` and only make additional checks that affect the warning output and success of compiler tasks, but not the bytecode output. In [a message in the mailing list](https://groups.google.com/d/msg/error-prone-discuss/B2aOPzx11lo/ZEdmkR5ZAgAJ) it is said that Error Prone uses "OpenJDK 9 javac", in terms of bytecode output. Could it be assured in the official docs?

**Comment by cushon** [comment]
Error Prone is a javac plugin, so the bytecode is the same as what you'd get from the javac. We redistribute a copy of javac (hosted here: https://github.com/google/error-prone-javac) so we can depend on a specific version of some of its internal APIs. Currently that javac version corresponds roughly to JDK 9 EA Build 159.

I'll try to clear that up in the documentation, thanks for the report.

**Comment by mattnelson** [comment]
Bumping this because an issue arose with the `2.0.21` release which includes the modularized javac which seems to be producing different bytecode which is now breaking other static analysis tools. Specifically the findbugs `OBL_UNSATISFIED_OBLIGATION` rule in regards to `try-with-resources` blocks. I haven't finished digging into it, but my hunch is that the new compiler is creating a different bytecode profile for the TWR block that findbugs doesn't recognize.

It should be very clear up front that errorprone is replacing javac instead of acting like all other static analysis tools that simply run some rules of the source/byte code without alteration.

[1] https://github.com/google/error-prone/issues/653#issuecomment-312134226

**Comment by cushon** [comment]
You may have encountered the changes to try-with-resources desugaring made by [JDK-7020499](https://bugs.openjdk.java.net/browse/JDK-7020499).

I still agree this is worth calling out in the documentation somewhere, but to re-iterate: Error Prone is a javac plugin that requires the OpenJDK 9 javac, which we redistribute an unmodified copy of. It is not diverging from the behaviour you'd get from compiling with a stock javac 9.

**Comment by cushon** [comment]
For JDK > 8 we're no longer recommending the `error-prone-javac` redistribution, using Error Prone as a `javac` `-Xplugin:` you get exactly the same bytecode output as `javac`.
