### ISSUE TITLE
CheckReturnValue: support more variants of "fail" in try/execute/fail/catch

### ISSUE THREAD

**Issue by michaelhixson** [google/error-prone#804]
Recently I had to add some `@SuppressWarnings("CheckReturnValue")` to my code because I upgraded from JUnit 4 to 5, and Error Prone no longer recognized the try/execute/fail/catch pattern in my code.  I eventually realized this is because `CheckReturnValue` looks for a specific set of "fail" methods and JUnit 5's is not one of them.  See the [relevant lines of `AbstractReturnValueIgnored`](https://github.com/google/error-prone/blob/d8f527aec08d86e34f7b56f07802ab1d496b493f/core/src/main/java/com/google/errorprone/bugpatterns/AbstractReturnValueIgnored.java#L244-L270).

It took me a long time to figure out what was going wrong and I'd like to save other people from the headache.

Would you be willing to accept a pull request that adds support for each of the following?

* [JUnit 5's `fail` method](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#fail-java.lang.String-)
* [testng's `fail` method](https://jitpack.io/com/github/cbeust/testng/master-6.12-g0ef9cdb-153/javadoc/org/testng/Assert.html#fail--)
* `throw new AssertionError(...)`

In order to add test cases that compile for JUnit 5 and testng, I think I would need to add those libraries as test-scope dependencies of the "core" module, in case that influences the decision.

**Comment by cushon** [comment]
Thanks for bringing this up. We'll probably want to add support for the new fail methods, but if you're using JUnit 5 I recommend using `assertThrows` instead of `try/execute/fail/catch`.

**Comment by jbduncan** [comment]
I agree with @cushon. `assertThrows` is the new "try/execute/fail/catch" in JUnit 5, so if migrating to `assertThrows` is feasible, that'd be my recommendation.

**Comment by michaelhixson** [comment]
@cushon So are you saying I should *not* create the pull request?

I was not aware of the `assertThrows` method, thanks.  Since `assertThrows` is (apparently) already supported by `CheckReturnValue`, perhaps it is worth updating [the documentation](https://github.com/google/error-prone/blame/6c6ebb8db9f510c54c840a4dfcda6a8d575c2ba3/docs/bugpattern/CheckReturnValue.md#L28-L48) to say so.  I could also include that in a PR...

(Not to muddy the waters, but this chain of comments has me wondering whether a new bug pattern would be worthwhile - one that detects try/execute/fail/catch in JUnit 5 and testng code and recommends using `assertThrows` instead.)

**Comment by cushon** [comment]
We're happy to take a PR for this. There isn't a great way to add a test since Error Prone uses JUnit 4, but that's fine.

> this chain of comments has me wondering whether a new bug pattern would be worthwhile - one that detects try/execute/fail/catch in JUnit 5 and testng code and recommends using assertThrows instead.

We have a refactoring for this but it hasn't been open-sourced yet. I can do that if there'd be interest. We also have checks for [`ExpectedException`](http://errorprone.info/bugpattern/ExpectedExceptionChecker) and the [`@Test(expected=...)`](http://errorprone.info/bugpattern/TestExceptionChecker) pattern that can be adapted to refactor all uses of those APIs to `assertThrows`. We've been migrated those APIs to `assertThrows` more aggressively because they're easier to mis-use than try/fail/catch.

**Comment by jbduncan** [comment]
@cushon I'm personally interested in seeing these refactorings/checks open-sourced! But if it would take away time that would otherwise be spent on designing & coding up support for [`--release`](https://github.com/google/error-prone/issues/784) and [Java 9](https://github.com/google/error-prone/issues/448), I'd personally prefer for those to take priority, if that would be both reasonable and feasible. :)

**Comment by michaelhixson** [comment]
I'm also interested in those `assertThrows` checks, for whatever that's worth.

**Comment by cushon** [comment]
The refactorings I mentioned earlier are now available: 42a9a65f103ec1b691b22a0afebee5305a6cd312.

**Comment by cushon** [comment]
Also `assertThrows` was [released in JUnit 4.13](https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md), so using it doesn't require JUnit 5 (or a snapshot release of JUnit 4) anymore.

I'd still take a PR to add more heuristics to `AbstractReturnValueIgnored` if anyone is interested in contributing that, but I'm going to close this we're not likely to get to it, since as mentioned above we're mostly using `assertThrows`.
