### ISSUE TITLE
Using error-prone with spring-boot maven plugin

### ISSUE THREAD

**Issue by skogie** [google/error-prone#834]
We are eager to use error-prone in our project, but I have yet to figure out how to include the plugin with the spring-boot-maven-plugin. Is it possible to get an example of how to integrate this plugin with spring-boot? That would be much appreciated.

**Comment by jbduncan** [comment]
Hi @skogie. Have you tried the Maven configuration suggested in the [installation](http://errorprone.info/docs/installation) instructions?

**Comment by skogie** [comment]
Yeah, but we are not using maven-compiler-plugin, but the spring-boot-maven-plugin instead. The project compiles but does not catch any errors. Like including a dead exception. Any suggestions?

**Comment by jbduncan** [comment]
Thanks for the clarification @skogie, but I'm not entirely sure if I've understood your problem yet.

Does spring-boot-maven-plugin compile Java source files to .class files instead of maven-compiler-plugin? If so, I wonder if spring-boot-maven-plugin has a way of changing the compiler to be used. (I searched for "javac" and "compiler" in the [Spring Boot Maven plugin docs](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-maven-plugin.html), but I've personally not found anything yet.)

But if spring-boot-maven-plugin _doesn't_ compile Java source files (because e.g. it delegates that task to another plugin), then have you tried using both spring-boot-maven-plugin and the suggested maven-compiler-plugin config together?

**Comment by Stephan202** [comment]
If your `pom.xml` doesn't contain a `maven-compiler-plugin` configuration section, you're probably inheriting it from a parent POM or otherwise depending on its default configuration. Running `mvn help:effective-pom` may provide some clues. In any case, adding a configuration section for the `maven-compiler-plugin` as documented should help. (We don't use the `spring-boot-maven-plugin`, but afaik it deals with creating a custom executable JAR, not with compilation itself.)

**Comment by skogie** [comment]
Yeah I assumed it was included in the spring-boot-maven-plugin, but it looks like i inherit it from the spring-boot-starter-parent (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter/pom.xml). My question remains tho, how to add the configuration to a parent-pom. It's unfortunate if we have to download and monkeypatch the official spring-boot-starter-parent to make this work.

**Comment by Stephan202** [comment]
I don't think there's a way around that. Looking at the XML snippet in the Error Prone documentation linked above, you could omit `source` and `target` elements, as well as the `maven-compiler-plugin`'s `version` tag. The other pieces are required.

**Comment by vorburger** [comment]
@skogie are you aware that Maven "merges" `plugin` declarations (and everything else..) from all parent POM **(s)** with your current POM to get the "effective" POM? Have you tried just putting the error-prone maven-compiler-plugin snippet into your POM? As @Stephan202 says, you can then remove what the Spring Boot parent POM already provides for you. You can use `mvn help:effective-pom` to see the result of the merge. And it should just work! Best of luck.

**Comment by skogie** [comment]
Excellent, it all works now! Just had to omit the conflicting version number! Thanks.

**Comment by tbroyer** [comment]
This would mean you didn't pass the `--add-exports`/`--add-opens`: https://errorprone.info/docs/installation#maven

**Comment by PascoalBayonne** [comment]
@tbroyer fantastic! Even reading the documentation I was not aware of the newer versions of Java. Added the mvn.jvm.config as mentioned in the documentation and now it works. Thanks
