### ISSUE TITLE
InconsistentOverloads published documentation is not up-to-date with sources of 2.1.3 release

### ISSUE THREAD

**Issue by vorburger** [google/error-prone#869]
I wanted to contribute a minor documentation update to http://errorprone.info/bugpattern/InconsistentOverloads to clarify that where that (currently) states _"@SuppressWarnings("InconsistentOverloads") to the enclosing element."_ it typically really means "class containing the method" as I had annotated the method itself and got confused why that suppression didn't work, until I found https://github.com/google/error-prone/issues/717 and understood.

Looking for the source of http://errorprone.info/bugpattern/InconsistentOverloads I found https://github.com/google/error-prone/blob/master/docs/bugpattern/overloading/InconsistentOverloads.md from https://github.com/google/error-prone/commit/9ed602aa88d0240db61a009f6c0d5798f7f0bf01, but that (at least as of writing this) is completely different content than what is currently on the public site, and on https://github.com/google/error-prone/blob/gh-pages/bugpattern/InconsistentOverloads.md ... 

Perhaps now that you have released 2.1.3 you need to re-run some job to update the gh-pages branch?

**Comment by vorburger** [comment]
BTW the 2.1.3 release on violations still prints _"(see http://errorprone.info/bugpattern/InconsistentOverloads)"_, but it seems that on re-publishing this will now be under in http://errorprone.info/bugpattern/overloading/InconsistentOverloads ?

**Comment by cushon** [comment]
Thanks - https://github.com/google/error-prone/blob/master/docs/bugpattern/overloading/InconsistentOverloads.md is at the wrong location, so it wasn't getting picked up by the doc generator. I will fix that.

I wonder though if we should support suppressing this check on individual methods, instead of updating the docs? The default handling of `SuppressWarnings` is based on which AST node the check matches on, and this one matches on classes and scans the members. We can make it recognize suppressions on the members too, e.g.:

https://github.com/google/error-prone/blob/b639ff7cdf418f2f6a5131b8561d628b6d5cfac7/core/src/main/java/com/google/errorprone/bugpatterns/ConstructorLeakChecker.java#L53

**Comment by vorburger** [comment]
@cushon support suppressing this check on individual methods is probably what https://github.com/google/error-prone/issues/717 was about? If I were you I would just (first) merge my https://github.com/google/error-prone/pull/870 and (then) move and re-publish the doc under this issue here, and be done with it for the very short term; until someone can pick up https://github.com/google/error-prone/issues/717. I would love to be that someone but am unlikely going to have the time for it, sorry!

**Comment by cushon** [comment]
I added support for `@SuppressWarnings` on methods in e7355b5191a3259c11b2e02d39ac6b64e7399be4., and the docs at http://errorprone.info/bugpattern/InconsistentOverloads include the rest of the explanation now.
