### ISSUE TITLE
Exclude inner classes annotated with @Nested from ClassCanBeStatic rule

### ISSUE THREAD

**Issue by uhafner** [google/error-prone#956]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?

2.2.0 (with maven.plugin 2.8.2)

### Does this issue reproduce with the latest release?

Yes

### What did you do?

JUnit 5 provides nested tests using an inner class (not static): See Example at  https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested 

If I use the rule **ClassCanBeStatic** on all my classes, then all those tests are flagged. 

### What did you expect to see?

An inner class with the annotation `@org.junit.jupiter.api.Nested` should not be flagged as warning.

### What did you see instead?

[WARNING] /Users/hafner/Development/jenkins/workspace/Pipeline/src/test/java/edu/hm/hafner/analysis/parser/dry/CodeDuplicationTest.java:[64,5] [ClassCanBeStatic] Inner class is non-static but does not reference enclosing class

**Comment by bobtiernay-okta** [comment]
Sadness :(

**Comment by dmdashenkov** [comment]
Hi. Is there any chance this issue is going to be fixed? With the latest update, this now is also relevant to some production code. For example, I have a number of `private` methods marked with an annotation. These methods are invoked via reflection. Currently, error-prone treats them as unused.

The same applies to the JUnit 5 factory methods. Those are not annotated with any kind of a special annotation. Instead, they are referenced by the name from method annotations in the same class.

**Comment by mohanaraosv** [comment]
This problem still exists [UnusedMethod] Private method 'errorEnumsProvider' which returns Stream<Arguments> is never used.
